### ISSUE TITLE
Doesn't send webp files in docker container

### ISSUE THREAD

**Issue by Diden05** [dimaskiddo/go-whatsapp-multidevice-rest#7] opened 2022-04-27 14:39 UTC
If I send the webp file as an image, then the file is not sent :(

**Comment by dimaskiddo** [comment] 2022-04-28 04:13
I can't reproduce it
It's work in my system

![image](https://user-images.githubusercontent.com/21129987/165675111-ab6a7b69-33c6-4497-949a-07adb2466c68.png)

![image](https://user-images.githubusercontent.com/21129987/165675179-68aad118-0d5f-461d-a82b-718c08f6337d.png)

WEBP file is from here:
https://www.gstatic.com/webp/gallery/1.webp

**Comment by dimaskiddo** [comment] 2022-04-28 04:18
The possibility is you need a webp mime data in your system
Since uploaded file type is parsed from uploaded file header content-type, then if your system can't recogneized it then it'll get wrong mime type

Please check your system mime data type. Make sure it's recognizing the WebP file
Since it's not reproduceable by me, then i'll temporary close this issue

Please re-open if my suggestion can't solve it
Cheers 🍻

**Comment by Diden05** [comment] 2022-04-28 06:14
Hey @dimaskiddo!
And yet it does not work, maybe you need some kind of library on the server?
Logging http://joxi.ru/EA4pj6PHXY6wyA
We get http://joxi.ru/8An0OBeCN4QjDm
Testing on your picture :(

**Comment by dimaskiddo** [comment] 2022-04-28 07:34
I can't open the logging image,
and still can't reproduce the issue with compiled version release v1.0.0

![image](https://user-images.githubusercontent.com/21129987/165700972-b341ffbc-afbc-42b7-87f7-338f0a8a339d.png)

Can you direct paste to github?

**Comment by dimaskiddo** [comment] 2022-04-28 07:43
Sorry pak @ibnux for mentioning you here, if you're in free time can you help me to try reproduce this issue in your side?
Thank you very much pak

**Comment by ibnux** [comment] 2022-04-28 07:53
@dimaskiddo ok will try it 👍

**Comment by dimaskiddo** [comment] 2022-04-28 08:27
Thank you so much pak @ibnux for your help, i'am so sorry pak 🙏

**Comment by Diden05** [comment] 2022-04-28 08:28
> I can't open the logging image, and still can't reproduce the issue with compiled version release v1.0.0
> 
> ![image](https://user-images.githubusercontent.com/21129987/165700972-b341ffbc-afbc-42b7-87f7-338f0a8a339d.png)
> 
> Can you direct paste to github?

![519b9e607b](https://user-images.githubusercontent.com/1879413/165710885-50e3ad55-1d64-4224-ac4b-360023bbd7c2.jpg)


![72eafce26d](https://user-images.githubusercontent.com/1879413/165710919-ab113866-4acd-4308-a0de-fbcbd9074320.jpg)

@dimaskiddo

**Comment by ibnux** [comment] 2022-04-28 09:13
Success send webp to my WA Gateway

using latest git pull ,, run on local macbook

static webp from here
https://developers.google.com/speed/webp/gallery1

animated webp from here
https://mathiasbynens.be/demo/animated-webp

<img width="1078" alt="Screen Shot 2022-04-28 at 16 10 12" src="https://user-images.githubusercontent.com/811955/165719040-bfcd6947-117e-49f7-a7b8-fa7061b156f0.png">

**Comment by Diden05** [comment] 2022-04-28 10:08
@ibnux @dimaskiddo I'm running this in docker, with the default Dockerfile. Maybe that's the issue, I don't know :(

**Comment by Diden05** [comment] 2022-04-28 10:38
I tried to send just a postman picture to which you gave a link, it says that "message": "Successfully Send Media Message" but the picture itself does not come to the recipient
![Doesnt send webp files · Issue 7](https://user-images.githubusercontent.com/1879413/165734796-b2119b58-1b9a-4aeb-b95d-625dad4ae05c.jpg)
.

**Comment by Diden05** [comment] 2022-04-28 13:38
@dimaskiddo If the phone to which you send the webp picture does not use the beta version of whatsapp, the picture will not come to this phone, if I start using the beta then the picture comes to the web version but still does not come to the phone.
Wonders.
So far I see only one way out, convert webp to png so that it does not depend on what version of whatsapp is on the receiving side

**Comment by dimaskiddo** [comment] 2022-04-28 16:04
Thanks pak @ibnux for helping me test it out
So @Diden05 the problem seem in your whatsapp client destination right? Not the Docker or the server
Just the client destination outadated so need to upgrade

For converting webp to png proposal is accepted but this only happend if meta is webp for backward compatible client

**Comment by Diden05** [comment] 2022-04-28 16:54
@dimaskiddo Whatsapp apps have been updated to the latest version, but they do not have multi-device beta enabled. I have implemented the conversion of webp-> png, I will put the code in order and I can lay it out, I strongly ask you not to beat me as a golang developer, I'm just starting :)

**Comment by dimaskiddo** [comment] 2022-04-28 17:04
I already implement convertion of webp to jpeg for smaller size in develop branch [adce8e9](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/adce8e94046a160cb89365203142afaa0802bda3)

Hmm beating you? i don't have concern of that, i'am just trying to contribute and full fill the request. Sounds wierd for me, it's joke or not i think it's your concern not mine 😐

**Closed by dimaskiddo** 2022-04-28 17:04 UTC

**Comment by dimaskiddo** [comment] 2022-04-28 17:11
I already implement convertion of webp to jpeg for smaller size in develop branch [adce8e9](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/adce8e94046a160cb89365203142afaa0802bda3)

**Comment by Diden05** [comment] 2022-04-28 17:14
jpeg doesn't know transparency, that's why I suggested PNG

**Comment by dimaskiddo** [comment] 2022-04-28 17:54
I just need change jpeg.Encoder to png.Encoder if you want it 😄 thanks for the idea and code propose

**Comment by Diden05** [comment] 2022-04-28 18:51
@dimaskiddo Thanx!
